[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "org.slashlib.py.agent"
version = "0.1.6"
license = "MIT"
dependencies = [
  "org.slashlib.py.configloader>=0.1.0"
]
authors = [
  { name="Dirk Brenckmann", email="db.developer@gmx.de" },
]
description = "python agent for inference handling"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/org-slashlib/org.slashlib.py.agent"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
asyncio_mode = "auto"
addopts = """
    -v  
    --cov 
    --cov=src/org/slashlib/py/agent 
    --cov-report=term-missing 
    --cov-report=xml:docs/reports/coverage/xml
    --cov-report=html:docs/reports/coverage/html
"""

[tool.coverage.run]
data_file = "docs/reports/coverage/.coverage"
source = ["src/org/slashlib/py/agent"]
omit = ["src/org/slashlib/py/agent/__main__.py"]

[tool.coverage.report]
show_missing = true
