# -*- coding: utf-8 -*-
# file src/org/slashlib/py/agent/inference_complements_for_ollama.py
# @AI:
# - INTEGRITY RULES:
#   - STRICT PRESERVATION: Do not remove, move, or modify ANY existing lines of code or comments 
#     unless they are the explicit target of the requested change. 
#   - DEBUG MARKERS: Commented-out code (e.g., debug prints) MUST be kept exactly where they are.
#   - WHITESPACE & STRUCTURE: Maintain all original empty lines and the existing file structure. 
#     Structural integrity takes precedence over "clean code" or "elegance".
#   - LEAD-IN/OUT: The very first and last lines (and all comments in between) are immutable anchors.
# - MAINTENANCE:
#   - Only update pydoc strings (args, returns, raises) if the function signature changes.
#   - Do NOT delete existing examples or descriptions in pydoc.
# - LANGUAGE: en-US for all comments and documentation.
#

# Python imports
import logging
import pathlib
import typing

# Third party imports
import ollama
import org.slashlib.py.configloader as config

# Internal imports
import org.slashlib.py.agent.inference_bases as inference


class OllamaInferenceResult(inference.InferenceResult):
    """
    Specific implementation of InferenceResult for Ollama.

    This class takes the raw dictionary response from the Ollama API, 
    validates its mandatory fields (role, content/tool_calls), and 
    provides standardized accessors for the Agent.
    """

    def __init__(self, raw_response: typing.Dict[str, typing.Any]):
        """
        Initialize and validate the Ollama response.

        Args:
            raw_response (Dict[str, Any]): The 'message' part of the Ollama API response.

        Raises:
            inference.InferencePayloadError: If the 'role' is missing or if both 
                'content' and 'tool_calls' are empty/None.
        """
        self._role = raw_response.get("role")
        self._content = raw_response.get("content")
        self._tool_calls = raw_response.get("tool_calls")

        if not self._role:
            raise inference.InferencePayloadError(f"Invalid Ollama response: 'role' is missing. Data: {raw_response}")
        
        # Note: content can be None if tool_calls are present, which is valid.
        if self._content is None and not self._tool_calls:
            raise inference.InferencePayloadError(f"Invalid Ollama response: Both 'content' and 'tool_calls' are empty.")

    @property
    def role(self) -> str:
        """
        The role of the message sender.

        Returns:
            str: Typically 'assistant'.
        """
        return self._role

    @property
    def content(self) -> typing.Optional[str]:
        """
        The text content of the model's response.

        Returns:
            Optional[str]: The message text or None if only tool calls are present.
        """
        return self._content

    @property
    def tool_calls(self) -> typing.Optional[typing.List[typing.Dict[str, typing.Any]]]:
        """
        A list of tool calls generated by the model.

        Returns:
            Optional[List[Dict[str, Any]]]: Standardized tool call objects or None.
        """
        return self._tool_calls

    def to_dict(self) -> typing.Dict[str, typing.Any]:
        """
        Converts the result into a standardized dictionary.

        Returns:
            Dict[str, Any]: A dictionary containing 'role', 'content', and 'tool_calls'.
        """
        return {
            "role": self._role,
            "content": self._content,
            "tool_calls": self._tool_calls
        }


class OllamaInferenceAdapter(inference.InferenceAdapter):
    """
    Inference Adapter for the Ollama API.

    Handles asynchronous communication with an Ollama server, including 
    parameter resolution from config and error mapping to the neutral 
    inference exception hierarchy.
    """

    def __init__(self):
        """
        Initialize the adapter and its logger.
        """
        self.log = logging.getLogger(f"org.slashlib.py.agent.{pathlib.Path(__file__).stem}.{self.__class__.__name__}")

    async def chat(
        self, 
        model: typing.Optional[str] = None, 
        messages: typing.List[typing.Dict[str, typing.Any]] = None, 
        tools: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = None,
        **kwargs
    ) -> inference.InferenceResult:
        """
        Sends a chat request to Ollama and returns a validated result.

        Resolves model parameters using a priority chain: 
        1. Explicit kwargs, 2. Method arguments, 3. pyproject.json via configloader.

        Args:
            model (Optional[str]): The model name. Defaults to config value.
            messages (List[Dict[str, Any]]): The message history/context.
            tools (Optional[List[Dict[str, Any]]]): JSON schemas of available tools.
            **kwargs: Additional parameters like 'timeout' or 'think'.

        Returns:
            inference.InferenceResult: An instance of OllamaInferenceResult.

        Raises:
            inference.InferenceConfigError: If the model is not found or config is invalid.
            inference.InferenceConnectionError: If the Ollama server is unreachable or times out.
            inference.InferencePayloadError: If the response from Ollama is malformed.
            inference.InferenceError: For any other unexpected errors during inference.
        """
        # Resolve parameters: priority is kwargs -> method arg -> pyproject.json
        target_model = model or kwargs.get("model", config.resolve("adapter.ollama.model"))
        timeout = kwargs.get("timeout", config.resolve("adapter.ollama.timeout"))
        think = kwargs.get("think", config.resolve("adapter.ollama.think"))

        try:
            self.log.debug(f"Ollama request: timeout={timeout}, model={target_model}, messages={messages}, tools={tools}, think={think}")
            
            client = ollama.AsyncClient(timeout=timeout)
            response = await client.chat(
                model=target_model,
                messages=messages,
                tools=tools,
                think=think
            )

            self.log.debug(f"Ollama response: {response}")
            
            message = response.get("message")
            if not message:
                raise inference.InferencePayloadError(f"Ollama API returned an empty response for model '{target_model}'.")

            return OllamaInferenceResult(message)

        except (ollama.ResponseError) as e:
            self.log.error(f"Ollama logical/config error: {e}", exc_info=True)
            raise inference.InferenceConfigError(f"Ollama model or config invalid: {str(e)}")
        except (ollama.RequestError) as e:
            self.log.error(f"Ollama communication error: {e}", exc_info=True)
            raise inference.InferenceConnectionError(f"Failed to connect to Ollama: {str(e)}")
        except inference.InferenceError:
            # Re-raise internal inference errors to prevent them from being caught by the general Exception block
            raise
        except Exception as e:
            self.log.error(f"Unexpected error in OllamaInferenceAdapter: {e}", exc_info=True)
            raise inference.InferenceError(f"Internal adapter error: {str(e)}")


__all__ = ["OllamaInferenceAdapter", "OllamaInferenceResult"]

# end of file src/org/slashlib/py/agent/inference_complements_for_ollama.py